### ISSUE TITLE
The "Update" action stopped to be ran 2 months ago

### ISSUE THREAD

**Issue by mems** [CMeeg/fnm-chocolatey#2]
It's look like GitHub don't like schedules on repository that don't have enough activity. The "Update" action is stopped running.
On the [page of workflows](https://github.com/CMeeg/fnm-chocolatey/actions/workflows/main.yml) it's written:

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

There is [some solutions](https://stackoverflow.com/a/69569866/470117) to keep it running, but I don't know if it's suitable for this repo

**Comment by CMeeg** [comment]
Thanks for raising this. I normally get an email when the workflow has been disabled, but GitHub have either stopped sending those or I missed it (I probably missed it!).

I re-enabled the workflow and ran it manually, but it was failing to run to completion so looking into that it turns out GitHub have made some changes to their release pages and those changes caused my script to fail.

Anyway, to cut a long story short I have fixed the issue and have successfully run the workflow to publish fnm v1.32.0 to chocolatey. It's currently awaiting review on their side, but that's usually an automated process so should hopefully be ready for download within a few hours.

Thanks for the links to the solutions for keeping workflows running - the solution that uses the GitHub API looks promising - I will take a look when I can as it will be better than me remembering to check my emails!
